"""Password and secret generator tool."""

from __future__ import annotations

import secrets
import string
from typing import Optional

from saladbox.tools.base import BaseTool


class PasswordTool(BaseTool):
    """Generate secure passwords and secrets."""

    @property
    def name(self) -> str:
        return "password"

    @property
    def description(self) -> str:
        return (
            "Generate secure random passwords, passphrases, API keys, and secrets. "
            "Customizable length and character sets. All generation uses cryptographically "
            "secure random number generation."
        )

    @property
    def parameters(self) -> dict:
        return {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string",
                    "enum": [
                        "password",
                        "passphrase",
                        "api_key",
                        "pin",
                        "hex_token",
                        "secret",
                    ],
                    "description": "Type of secret to generate",
                },
                "length": {
                    "type": "integer",
                    "description": "Length of the generated secret (default varies by type)",
                },
                "include_uppercase": {
                    "type": "boolean",
                    "description": "Include uppercase letters (default: true)",
                },
                "include_lowercase": {
                    "type": "boolean",
                    "description": "Include lowercase letters (default: true)",
                },
                "include_numbers": {
                    "type": "boolean",
                    "description": "Include numbers (default: true)",
                },
                "include_symbols": {
                    "type": "boolean",
                    "description": "Include special symbols (default: true)",
                },
                "word_count": {
                    "type": "integer",
                    "description": "Number of words for passphrase (default: 4)",
                },
                "separator": {
                    "type": "string",
                    "description": "Separator for passphrase words (default: '-')",
                },
                "count": {
                    "type": "integer",
                    "description": "Number of passwords to generate (default: 1)",
                },
            },
            "required": ["action"],
        }

    WORD_LIST = [
        "able",
        "acid",
        "aged",
        "also",
        "area",
        "army",
        "away",
        "baby",
        "back",
        "ball",
        "band",
        "bank",
        "base",
        "bath",
        "bear",
        "beat",
        "been",
        "beer",
        "bell",
        "belt",
        "best",
        "bill",
        "bird",
        "blow",
        "blue",
        "boat",
        "body",
        "bomb",
        "bond",
        "bone",
        "book",
        "boom",
        "born",
        "boss",
        "both",
        "bowl",
        "bulk",
        "burn",
        "bush",
        "busy",
        "call",
        "calm",
        "came",
        "camp",
        "card",
        "care",
        "case",
        "cash",
        "cast",
        "cell",
        "chat",
        "chip",
        "city",
        "club",
        "coal",
        "coat",
        "code",
        "cold",
        "come",
        "cook",
        "cool",
        "cope",
        "copy",
        "core",
        "cost",
        "crew",
        "crop",
        "dark",
        "data",
        "date",
        "dawn",
        "days",
        "dead",
        "deal",
        "dean",
        "dear",
        "debt",
        "deep",
        "deny",
        "desk",
        "diet",
        "dirt",
        "dish",
        "disk",
        "door",
        "dose",
        "down",
        "draw",
        "drew",
        "drop",
        "drug",
        "dual",
        "duke",
        "dust",
        "duty",
        "each",
        "earn",
        "ease",
        "east",
        "easy",
        "edge",
        "else",
        "even",
        "ever",
        "evil",
        "exit",
        "face",
        "fact",
        "fail",
        "fair",
        "fall",
        "fame",
        "farm",
        "fast",
        "fate",
        "fear",
        "feed",
        "feel",
        "feet",
        "fell",
        "felt",
        "file",
        "fill",
        "film",
        "find",
        "fine",
        "fire",
        "firm",
        "fish",
        "five",
        "flat",
        "flow",
        "folk",
        "food",
        "foot",
        "ford",
        "form",
        "fort",
        "four",
        "free",
        "from",
        "fuel",
        "full",
        "fund",
        "gain",
        "game",
        "gate",
        "gave",
        "gear",
        "gene",
        "gift",
        "girl",
        "give",
        "glad",
        "goal",
        "goes",
        "gold",
        "golf",
        "gone",
        "good",
        "gray",
        "grew",
        "grow",
        "gulf",
        "hair",
        "half",
        "hall",
        "hand",
        "hang",
        "hard",
        "harm",
        "hate",
        "have",
        "head",
        "hear",
        "heat",
        "held",
        "hell",
        "help",
        "here",
        "hero",
        "high",
        "hill",
        "hire",
        "hold",
        "hole",
        "holy",
        "home",
        "hope",
        "host",
        "hotel",
        "hour",
        "huge",
        "hung",
        "hunt",
        "hurt",
        "idea",
        "inch",
        "into",
        "iron",
        "item",
        "jane",
        "jean",
        "john",
        "join",
        "jump",
        "jury",
        "just",
        "keen",
        "keep",
        "kent",
        "kept",
        "kick",
        "kill",
        "kind",
        "king",
        "knee",
        "knew",
        "know",
        "lack",
        "lady",
        "laid",
        "lake",
        "land",
        "lane",
        "last",
        "late",
        "lead",
        "left",
        "less",
        "life",
        "lift",
        "like",
        "line",
        "link",
        "list",
        "live",
        "load",
        "loan",
        "lock",
        "long",
        "look",
        "lord",
        "lose",
        "loss",
        "lost",
        "love",
        "luck",
        "made",
        "mail",
        "main",
        "make",
        "male",
        "mall",
        "many",
        "mark",
        "mars",
        "mass",
        "matt",
        "meal",
        "mean",
        "meat",
        "meet",
        "menu",
        "mere",
        "mild",
        "mile",
        "milk",
        "mill",
        "mind",
        "mine",
        "miss",
        "mode",
        "mood",
        "moon",
        "more",
        "most",
        "move",
        "much",
        "must",
        "name",
        "navy",
        "near",
        "neck",
        "need",
        "news",
        "next",
        "nice",
        "night",
        "nine",
        "none",
        "nose",
        "note",
        "nova",
        "nuclear",
        "okay",
        "once",
        "only",
        "onto",
        "open",
        "oral",
        "over",
        "pace",
        "pack",
        "page",
        "paid",
        "pain",
        "pair",
        "palm",
        "park",
        "part",
        "pass",
        "past",
        "path",
        "peak",
        "pick",
        "pine",
        "pink",
        "pipe",
        "plan",
        "play",
        "plot",
        "plus",
        "poll",
        "pool",
        "poor",
        "port",
        "post",
        "pull",
        "pure",
        "push",
        "race",
        "rail",
        "rain",
        "rank",
        "rare",
        "rate",
        "read",
        "real",
        "rear",
        "rely",
        "rent",
        "rest",
        "rice",
        "rich",
        "ride",
        "ring",
        "rise",
        "risk",
        "road",
        "rock",
        "role",
        "roll",
        "roof",
        "room",
        "root",
        "rose",
        "rule",
        "rush",
        "ruth",
        "safe",
        "said",
        "sake",
        "sale",
        "salt",
        "same",
        "sand",
        "save",
        "seat",
        "seed",
        "seek",
        "seem",
        "seen",
        "self",
        "sell",
        "send",
        "sent",
        "ship",
        "shop",
        "shot",
        "show",
        "shut",
        "sick",
        "side",
        "sign",
        "silk",
        "site",
        "size",
        "skin",
        "slip",
        "slow",
        "snow",
        "soft",
        "soil",
        "sold",
        "sole",
        "some",
        "song",
        "soon",
        "sort",
        "soul",
        "spot",
        "star",
        "stay",
        "step",
        "stop",
        "such",
        "suit",
        "sure",
        "take",
        "tale",
        "talk",
        "tall",
        "tank",
        "tape",
        "task",
        "team",
        "tell",
        "tend",
        "term",
        "test",
        "text",
        "than",
        "that",
        "them",
        "then",
        "they",
        "thin",
        "this",
        "thus",
        "till",
        "time",
        "tiny",
        "told",
        "toll",
        "tone",
        "tony",
        "took",
        "tool",
        "tour",
        "town",
        "tree",
        "trip",
        "true",
        "tune",
        "turn",
        "twin",
        "type",
        "unit",
        "upon",
        "used",
        "user",
        "vary",
        "vast",
        "very",
        "vice",
        "view",
        "vote",
        "wage",
        "wait",
        "wake",
        "walk",
        "wall",
        "want",
        "ward",
        "warm",
        "wash",
        "wave",
        "ways",
        "weak",
        "wear",
        "week",
        "well",
        "went",
        "were",
        "west",
        "what",
        "when",
        "wide",
        "wife",
        "wild",
        "will",
        "wind",
        "wine",
        "wing",
        "wire",
        "wise",
        "wish",
        "with",
        "wolf",
        "wood",
        "word",
        "wore",
        "work",
        "wrap",
        "yard",
        "yeah",
        "year",
        "your",
        "zero",
        "zone",
        "zoom",
    ]

    async def execute(
        self,
        action: str,
        length: Optional[int] = None,
        include_uppercase: bool = True,
        include_lowercase: bool = True,
        include_numbers: bool = True,
        include_symbols: bool = True,
        word_count: int = 4,
        separator: str = "-",
        count: int = 1,
    ) -> str:
        try:
            results = []

            for _ in range(max(1, min(count, 10))):
                if action == "password":
                    pwd = self._generate_password(
                        length or 16,
                        include_uppercase,
                        include_lowercase,
                        include_numbers,
                        include_symbols,
                    )
                    results.append(pwd)

                elif action == "passphrase":
                    phrase = self._generate_passphrase(word_count, separator)
                    results.append(phrase)

                elif action == "api_key":
                    key = self._generate_api_key(length or 32)
                    results.append(key)

                elif action == "pin":
                    pin = self._generate_pin(length or 6)
                    results.append(pin)

                elif action == "hex_token":
                    token = self._generate_hex_token(length or 32)
                    results.append(token)

                elif action == "secret":
                    secret = self._generate_secret(length or 32)
                    results.append(secret)

                else:
                    return f"Unknown action: {action}"

            if len(results) == 1:
                return f"Generated {action}:\n{results[0]}"
            else:
                return f"Generated {len(results)} {action}s:\n" + "\n".join(results)

        except Exception as e:
            return f"Error: {str(e)}"

    def _generate_password(
        self, length: int, upper: bool, lower: bool, numbers: bool, symbols: bool
    ) -> str:
        length = max(8, min(128, length))

        charset = ""
        if upper:
            charset += string.ascii_uppercase
        if lower:
            charset += string.ascii_lowercase
        if numbers:
            charset += string.digits
        if symbols:
            charset += "!@#$%^&*()_+-=[]{}|;:,.<>?"

        if not charset:
            charset = string.ascii_letters + string.digits

        return "".join(secrets.choice(charset) for _ in range(length))

    def _generate_passphrase(self, word_count: int, separator: str) -> str:
        word_count = max(3, min(10, word_count))
        words = [secrets.choice(self.WORD_LIST) for _ in range(word_count)]
        numbers = str(secrets.randbelow(100))
        words.append(numbers)
        return separator.join(words)

    def _generate_api_key(self, length: int) -> str:
        length = max(16, min(64, length))
        charset = string.ascii_letters + string.digits
        return "".join(secrets.choice(charset) for _ in range(length))

    def _generate_pin(self, length: int) -> str:
        length = max(4, min(12, length))
        return "".join(secrets.choice(string.digits) for _ in range(length))

    def _generate_hex_token(self, length: int) -> str:
        length = max(16, min(128, length))
        byte_length = (length + 1) // 2
        return secrets.token_hex(byte_length)[:length]

    def _generate_secret(self, length: int) -> str:
        length = max(16, min(128, length))
        return secrets.token_urlsafe(length)[:length]
